config/routes.rb
Rails.application.routes.draw do
  resources :prices
  resources :activities
  resources :guestlists
  resources :interests
  resources :events
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/guestlist.rb
class Guestlist < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/controllers/guestlists_controller.rb
class GuestlistsController < ApplicationController
  before_action :set_guestlist, only: [:show, :edit, :update, :destroy]

  # GET /guestlists
  # GET /guestlists.json
  def index
    @guestlists = Guestlist.all
  end

  # GET /guestlists/1
  # GET /guestlists/1.json
  def show
  end

  # GET /guestlists/new
  def new
    @guestlist = Guestlist.new
  end

  # GET /guestlists/1/edit
  def edit
  end

  # POST /guestlists
  # POST /guestlists.json
  def create
    @guestlist = Guestlist.new(guestlist_params)

    respond_to do |format|
      if @guestlist.save
        format.html { redirect_to @guestlist, notice: 'Guestlist was successfully created.' }
        format.json { render :show, status: :created, location: @guestlist }
      else
        format.html { render :new }
        format.json { render json: @guestlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guestlists/1
  # PATCH/PUT /guestlists/1.json
  def update
    respond_to do |format|
      if @guestlist.update(guestlist_params)
        format.html { redirect_to @guestlist, notice: 'Guestlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @guestlist }
      else
        format.html { render :edit }
        format.json { render json: @guestlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guestlists/1
  # DELETE /guestlists/1.json
  def destroy
    @guestlist.destroy
    respond_to do |format|
      format.html { redirect_to guestlists_url, notice: 'Guestlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guestlist
      @guestlist = Guestlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guestlist_params
      params.require(:guestlist).permit(:user_id, :event_id)
    end
end

app/helpers/guestlists_helper.rb
module GuestlistsHelper
end

app/views/guestlists/_form.html.erb
<%= form_with(model: guestlist, local: true) do |form| %>
  <% if guestlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(guestlist.errors.count, "error") %> prohibited this guestlist from being saved:</h2>

      <ul>
      <% guestlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.number_field :event_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/guestlists/edit.html.erb
<h1>Editing Guestlist</h1>

<%= render 'form', guestlist: @guestlist %>

<%= link_to 'Show', @guestlist %> |
<%= link_to 'Back', guestlists_path %>

app/views/guestlists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Guestlists</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guestlists.each do |guestlist| %>
      <tr>
        <td><%= guestlist.user_id %></td>
        <td><%= guestlist.event_id %></td>
        <td><%= link_to 'Show', guestlist %></td>
        <td><%= link_to 'Edit', edit_guestlist_path(guestlist) %></td>
        <td><%= link_to 'Destroy', guestlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guestlist', new_guestlist_path %>

app/views/guestlists/new.html.erb
<h1>New Guestlist</h1>

<%= render 'form', guestlist: @guestlist %>

<%= link_to 'Back', guestlists_path %>

app/views/guestlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @guestlist.user_id %>
</p>

<p>
  <strong>Event:</strong>
  <%= @guestlist.event_id %>
</p>

<%= link_to 'Edit', edit_guestlist_path(@guestlist) %> |
<%= link_to 'Back', guestlists_path %>