config/routes.rb
Rails.application.routes.draw do
  resources :prices
  resources :activities
  resources :guestlists
  resources :interests
  resources :events
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :interest
  belongs_to :event
  belongs_to :price
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @activity = Activity.find(params[:id])
  end

  # GET /activities/new
  def new
    @activity = Activity.new
    @interests = Interest.all
    @prices = Price.all
    @events = Event.all

    # [{:k => 1, :val => 1}, {:k => 2, :val => 2}]
  end

  # GET /activities/1/edit
  def edit
    @activity = Activity.find(params[:id])
    @interests = Interest.all
    @prices = Price.all
  end

  # POST /activities
  # POST /activities.json
  def create
    @interests = Interest.all
    @prices = Price.all
      # byebug
    @activity = Activity.new(activity_params)



    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update

    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:interest_id, :event_id, :food, :cover, :booze, :price_id)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_with(model: activity, local: true) do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Category" %>
    <%= form.collection_select :interest_id, @interests, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.collection_select :event_id, @events, :id, :name %>
  </div>

  <div class="field">
    <%= form.label 'Will food be available?' %>
    <%= form.check_box:food %>
  </div>

  <div class="field">
    <%= form.label 'Is there a cover?' %>
    <%= form.check_box :cover %>
  </div>

  <div class="field">
    <%= form.label 'Will alcohol be served (21+)?' %>
    <%= form.check_box :booze %>
  </div>

  <div class="field">
    <%= form.label 'Price Range?' %>
    <%= form.collection_select :price_id, @prices, :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Activities</h1>

<table>
  <thead>
    <tr>
      <th>Interest</th>
      <th>Event</th>
      <th>Food</th>
      <th>Cover</th>
      <th>Booze</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.interest_id %></td>
        <td><%= activity.event_id %></td>
        <td><%= activity.food %></td>
        <td><%= activity.cover %></td>
        <td><%= activity.booze %></td>
        <td><%= activity.price %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Interest:</strong>
  <%= @activity.interest_id %>
</p>

<p>
  <strong>Event:</strong>
  <%= @activity.event_id %>
</p>

<p>
  <strong>Food:</strong>
  <%= @activity.food %>
</p>

<p>
  <strong>Cover:</strong>
  <%= @activity.cover %>
</p>

<p>
  <strong>Booze:</strong>
  <%= @activity.booze %>
</p>

<p>
  <strong>Price:</strong>
  <%= @activity.price.name %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>